DOC: 2024 updates
Add WebAssembly Introduction.

Remove Docker configuration and provide more detailed, native
development setup instructions.

Logo citation:

  OpenAI. (2024). ChatGPT (4) [Large language model]. https://chat.openai.com

Remove 8_Machine_Learning.ipynb, because fails to run with:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[3], line 7
      5 # Segment the hippocampus
      6 img_numpy = itk.array_from_image(itk_img)[np.newaxis, :]
----> 7 output_softmax = predictor.predict(torch.from_numpy(img_numpy))
      8 view(output_softmax[0])

File ~/src/torch_nnunet/nnunet/inference/torch_predict.py:111, in TorchPredictor.predict(self, data)
    104     softmax.append(self.trainer.predict_preprocessed_data_return_seg_and_softmax(
    105         data, all_in_gpu=False))
    106     # print(softmax[-1].shape)
    107
    108 # print('[0]', softmax[0])
    109 # print('[1]', softmax[1])
    110 # breakpoint()
--> 111 softmax = np.vstack(softmax)
    112 return np.mean(softmax, 0)

File ~/bin/micromamba/envs/itk-course/lib/python3.11/site-packages/numpy/core/shape_base.py:286, in vstack(tup, dtype, casting)
    219 @array_function_dispatch(_vhstack_dispatcher)
    220 def vstack(tup, *, dtype=None, casting="same_kind"):
    221     """
    222     Stack arrays in sequence vertically (row wise).
    223
   (...)
    284
    285     """
--> 286     arrs = atleast_2d(*tup)
    287     if not isinstance(arrs, list):
    288         arrs = [arrs]

File ~/bin/micromamba/envs/itk-course/lib/python3.11/site-packages/numpy/core/shape_base.py:121, in atleast_2d(*arys)
    119 res = []
    120 for ary in arys:
--> 121     ary = asanyarray(ary)
    122     if ary.ndim == 0:
    123         result = ary.reshape(1, 1)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.
```